=== Kuhneto/Internettechnologien/PraktikumITT1/SML.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Meisterschaft (Beginn, Ende, Mannschaft+,Spiel+)>
<!ATTLIST Meisterschaft typ (EM|WM) #IMPLIED>
<!ELEMENT Beginn (#PCDATA)>
<!ELEMENT Ende (#PCDATA)>
<!ELEMENT Mannschaft (Name, Land, Trainer, Spieler+, Erfolg*)>
<!ATTLIST Mannschaft id ID #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Land (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Spieler EMPTY>
<!ATTLIST Spieler position (Torwart|Verteidiger|Mittelfeld|StÃ¼rmer) #REQUIRED>
<!ELEMENT Erfolg EMPTY>
<!ATTLIST Erfolg
	Freitext	CDATA #IMPLIED
	Titel		CDATA #IMPLIED
	Jahr		CDATA #IMPLIED
>
<!ELEMENT Spiel EMPTY>
<!ATTLIST Spiel
	heim		ENTITY #REQUIRED
	gast		ENTITY #REQUIRED
	ergebnis	CDATA #IMPLIED
>

=== Kuhneto/Internettechnologien/PraktikumITT1/SML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PraktikumITT1 SYSTEM "SML.dtd">

<Meisterschaft>
<Beginn>01.06.2022</Beginn>
<Ende>15.09.2023</Ende>

<Mannschaft id = "FCB1">
<Name>FC Bayern</Name>
<Land>Deutschland</Land>
<Trainer>Julian Nagelsmann</Trainer>
<Spieler position = "Torwart"></Spieler>
<Spieler position = "Verteidiger"></Spieler>
</Mannschaft>

<Mannschaft id = "FCM1">
<Name>Real Madrid</Name>
<Land>Spanien</Land>
<Trainer>Xavi Alonso</Trainer>
<Spieler position = "Torwart"></Spieler>
<Spieler position = "Verteidiger"></Spieler>
</Mannschaft>

<Spiel heim = "FCB1" gast = "FCM1"></Spiel>
</Meisterschaft>
